### ISSUE TITLE
/practitioner

### ISSUE THREAD

**Issue by Lance-Gee** [liamandaidan/HomeHospital#116]
- [x] login screen - make login button assessable after entering email - Liam
- [x] don't show elements until user has been selected, so hide empty name, address, etc.. - Ridge
- [x] create toast for check in progress when new request has been submitted - Liam
- [x] after practitioner has checked in patient make sure page updates - Our latest branch version has this 
- [x] if possible show the role of the practitioner - **Lance**
- [x] update navbar to reflect username and avatar - **Lance**
- [x] Update refresh to retrieving new info - Lance + Liam

**Comment by liamandaidan** [comment]
So i think we just cut this
