### ISSUE TITLE
/admin

### ISSUE THREAD

**Issue by Lance-Gee** [liamandaidan/HomeHospital#117]
- [x] login screen - robyn
- [ ] edit practitioner- robyn
- [x] delete users - robyn
- [x] create users - robyn
** an admin will not be able to edit patient information, only delete. 

- [ ] remove notifications from navbar
- [x] login screen - make login button assessable after entering email

**Comment by rawbz** [comment]
update: waiting on backend team to create routes to complete page

**Comment by rawbz** [comment]
complete! :)
