### ISSUE TITLE
/Comment Code

### ISSUE THREAD

**Issue by Lance-Gee** [liamandaidan/HomeHospital#129]
- [x] Comment for all pages
- [x] Remove console.log - liam
- [x] Remove comments

**Comment by rawbz** [comment]
Robyn comment list: 

- [ ] editPatient
- [ ] ManageAdmin
- [ ] ManagePatient
- [ ] ManagePractitioner
- [ ] ManageUser
- [ ] PatientInfo
- [ ] SymptomsForm
- [ ] SymptomsTable
- [ ] ValidateAdminInfo
- [ ] ValidatePracInfo
- [ ] EditProfile - page
- [ ] Symptoms - page
- [ ] Admin - page
- [ ] AdminLogin - page
