### ISSUE TITLE
/admin

### ISSUE THREAD

**Issue by liamandaidan** [liamandaidan/HomeHospital#137]
- [x] Manage admin -> if there is an error doesn't show the user where the error is right away
- [x] Manage users -> click it should bring you back to users
- [x] remove console logs

**Comment by liamandaidan** [comment]
![image](https://user-images.githubusercontent.com/84680661/163257103-fe03077b-e22c-4269-9da0-5ebbf15090ab.png)
Lets get this to look like this:
![image](https://user-images.githubusercontent.com/84680661/163257473-f3009d29-3c39-4098-a4ef-7262152db0e7.png)

**Comment by liamandaidan** [comment]
I can take that on too if u need

**Comment by rawbz** [comment]
all good @liamandaidan ! I changed it :)
