### ISSUE TITLE
ErrorPage Component Mockup 🙃 

### ISSUE THREAD

**Issue by liamandaidan** [liamandaidan/HomeHospital#27]
Mockup and complete entire page.

**Comment by RidgeBnz** [comment]
![image](https://user-images.githubusercontent.com/84418684/155642265-de098351-04fc-4f30-b12b-ebd77415094b.png)
![image](https://user-images.githubusercontent.com/84418684/155642298-b41b28fd-03e0-4068-916a-c2924b50bf36.png)
![image](https://user-images.githubusercontent.com/84418684/155642675-c6702cdf-9d1a-49bb-8ed3-3c76725eb85f.png)

**Comment by RidgeBnz** [comment]
@liamandaidan, @Lance-Gee , @rawbz. Here are some 404 error page mockups I did. Thoughts and suggestions are welcomed.

**Comment by rawbz** [comment]
Great Job @RidgeBnz! I like the look of the middle one (frame 6) but i think the first one (frame 5) is easier to read. If we went with frame 6, I would lighten the image a bit more in the background just so the text is easier to read or maybe make the image smaller and raise the text a bit away from the busy part of the image.

**Comment by Lance-Gee** [comment]
@RidgeBnz I agree with @rawbz. Overall looks good.
