### ISSUE TITLE
 ❓ ForgotPassword Component Mockup

### ISSUE THREAD

**Issue by liamandaidan** [liamandaidan/HomeHospital#28]
Mockup and complete the entire page.

**Comment by liamandaidan** [comment]
![image](https://user-images.githubusercontent.com/84680661/155058934-8eea0bf4-ab07-4b21-9359-c104864f7c61.png)

**Comment by liamandaidan** [comment]
@RidgeBnz, @rawbz, @Lance-Gee thoughts?

**Comment by RidgeBnz** [comment]
@liamandaidan Looks good to me!

**Comment by Lance-Gee** [comment]
@liamandaidan looks good, a few suggestions.

1. Maybe add a back button beside the submit button in case someone mistakenly clicked on the forgot password button.
2. For the second page should it pop an alert with the message instead, and then redirect to the login page?

**Comment by rawbz** [comment]
@liamandaidan I agree with Lance about the back button and an alert to notify the user to check the email, then redirect to the login. Otherwise, looks great!

**Comment by liamandaidan** [comment]
Thanks for the feedback everyone, I will work to incorporate all of your suggestions! @Lance-Gee, I will 100% do 1. For the second page, It's totally up to what we choose. In my experience with forgetting passwords, they typically redirect as shown in my picture above
