### ISSUE TITLE
UserPage 

### ISSUE THREAD

**Issue by liamandaidan** [liamandaidan/HomeHospital#29]
Creation of user page! Can assign more people later as needed to help complete the issue.

**Comment by Lance-Gee** [comment]
I have created the navbar component for the user page, it's on lancebranch if you want to download and play with the component. Let me know your thoughts.
![image](https://user-images.githubusercontent.com/90357707/156944036-56abb7bb-fcc0-46cb-bfd3-ee994cd8c933.png)
@liamandaidan @rawbz @RidgeBnz

**Comment by liamandaidan** [comment]
> I have created the navbar component for the user page, it's on lancebranch if you want to download and play with the component. Let me know your thoughts. ![image](https://user-images.githubusercontent.com/90357707/156944036-56abb7bb-fcc0-46cb-bfd3-ee994cd8c933.png) @liamandaidan @rawbz @RidgeBnz

It looks good to me! I would consider adding an addition tab that includes settings, in case we give users an option to change settings within the app at a later point. 
![image](https://user-images.githubusercontent.com/84680661/156945640-b38a23a5-a5c7-4911-8512-ded250905532.png)
